"""Typing 「台積電」 and ending up with a symbol that actually prices.

The owner's complaint, in their words: 「輸入欄位使用者不會知道要如何填，通常是打
台積電或2330這種代表性指標」. What the app needed was 2330.TW, and nothing
anywhere told anybody that.

Both of the things they would naturally type failed, and both failed quietly:

  「台積電」 was accepted by the watchlist, stored, and then asked for by every
  poll. Yahoo has no such symbol, so no price ever came back -- no row, no
  error, and no alert from an entry that looked correctly configured.

  「2330」 is worse. Yahoo resolves a bare 2330 to a Japanese OTC company, so it
  DOES price -- the wrong company's price, delivered with total confidence.
  For an alerting product that is the most dangerous outcome available.

The rule this module is built around: offer candidates, never substitute. A
watchlist silently pointing at the wrong company is worse than an input that
was refused.
"""

import pytest

from app.models.enums import DataSource
from app.services import symbol_search
from app.services.symbol_search import normalise, search


def _symbols(query: str) -> list[str]:
    return [match.symbol for match in search(query)]


# --- the bundled table is real ----------------------------------------------


def test_the_listings_table_is_actually_bundled():
    """Everything else here is meaningless if the data file did not ship. It
    is generated by scripts/refresh_tw_listings.py and committed on purpose --
    an app that has to reach TWSE before it can add a stock to a watchlist has
    acquired a runtime dependency it does not need."""
    rows = symbol_search._listings()

    assert len(rows) > 1500, f"only {len(rows)} listings; is app/data/tw_listings.json present?"
    assert symbol_search.listings_generated_at()


def test_both_boards_are_present():
    """上櫃 is not a rounding error -- 環球晶 and friends live there, and a table
    with only 上市 would reject them as unknown."""
    suffixes = {row["symbol"].split(".")[-1] for row in symbol_search._listings()}

    assert suffixes == {"TW", "TWO"}


# --- what the owner actually types ------------------------------------------


def test_the_chinese_name_finds_the_stock():
    """The whole reason a bundled table exists: Yahoo's search answers HTTP 400
    to any query containing Chinese."""
    assert "2330.TW" in _symbols("台積電")


def test_the_chinese_name_is_the_FIRST_result_not_the_ninth():
    """An exact short-name match buried under companies whose full name merely
    contains those characters makes the picker useless."""
    assert _symbols("台積電")[0] == "2330.TW"


def test_a_bare_code_offers_the_qualified_symbol():
    assert _symbols("2330")[0] == "2330.TW"


def test_an_otc_code_gets_the_TWO_suffix_not_TW():
    """Getting the board wrong produces a symbol that does not price at all,
    which at least fails loudly -- but it fails on the owner, at the moment
    they were trying to set up an alert."""
    assert _symbols("6488")[0] == "6488.TWO"


def test_an_already_correct_symbol_is_confirmed_with_its_company_name():
    """Confirming matters: a typo'd digit is still a perfectly well-formed
    symbol, and 2231.TW instead of 2330.TW would never announce itself."""
    matches = search("2330.TW")

    assert matches[0].symbol == "2330.TW"
    assert "台積電" in matches[0].name


def test_a_lowercase_suffix_is_understood():
    assert _symbols("2330.tw")[0] == "2330.TW"


def test_a_partial_chinese_name_still_finds_it():
    assert "2330.TW" in _symbols("台積")


def test_a_us_ticker_is_offered_but_marked_as_unconfirmed():
    """There is no bundled table for US listings, so this is a guess from the
    shape of the input. Saying so is the difference between a suggestion and a
    claim."""
    matches = search("AAPL")

    assert matches[0].symbol == "AAPL"
    assert matches[0].verified is False
    assert matches[0].data_source is DataSource.YFINANCE


def test_a_taiwanese_result_IS_confirmed():
    assert search("2330")[0].verified is True


def test_a_binance_pair_is_recognised_as_crypto():
    matches = search("BTCUSDT")

    assert matches[0].symbol == "BTCUSDT"
    assert matches[0].data_source is DataSource.BINANCE


def test_nonsense_returns_nothing_rather_than_a_plausible_guess():
    """An empty list is a real answer -- it means this app cannot price that --
    and it is what stops a watchlist row being created that never alerts."""
    assert search("這不是一支股票") == []


def test_an_empty_query_is_not_an_error():
    assert search("") == []
    assert search("   ") == []


def test_results_are_capped():
    """The picker is a dropdown on a phone, not a report."""
    assert len(search("科技", limit=5)) <= 5


# --- normalising what gets stored -------------------------------------------


@pytest.mark.parametrize("raw", ["aapl", " AAPL ", "AAPL", "  aapl  "])
def test_latin_symbols_normalise_to_one_stored_form(raw):
    """Three watchlist rows for the same stock is three separate polls and
    three separate alerts."""
    assert normalise(raw) == "AAPL"


def test_chinese_is_left_exactly_as_typed():
    """Upper-casing it would be meaningless, and any transformation here edges
    towards the guessing this module refuses to do."""
    assert normalise(" 台積電 ") == "台積電"


def test_a_taiwanese_symbol_normalises_its_suffix():
    assert normalise("2330.tw") == "2330.TW"


# --- refusing what can never work -------------------------------------------


def test_a_company_name_is_refused_with_the_answer_in_the_message():
    """The old behaviour accepted it and produced a row that never priced."""
    reason = symbol_search.looks_unpriceable("台積電")

    assert reason
    assert "2330" in reason


def test_a_bare_taiwanese_code_is_refused_and_the_reason_is_the_dangerous_one():
    """This is the one that would otherwise have worked, on the wrong company."""
    reason = symbol_search.looks_unpriceable("2330")

    assert reason
    assert "2330.TW" in reason


def test_a_bare_otc_code_is_told_about_TWO_specifically():
    reason = symbol_search.looks_unpriceable("6488")

    assert reason and "6488.TWO" in reason


@pytest.mark.parametrize("symbol", ["2330.TW", "6488.TWO", "AAPL", "BTCUSDT", "BRK-B"])
def test_things_that_can_price_are_left_alone(symbol):
    assert symbol_search.looks_unpriceable(symbol) is None


def test_an_unknown_us_ticker_is_still_allowed_through():
    """A whitelist would reject every newly listed company and every ticker the
    bundled table has never heard of. Being unable to add a stock is a worse
    failure than adding one that turns out not to price -- the latter shows up
    immediately as a missing quote."""
    assert symbol_search.looks_unpriceable("ZZZZ") is None


def test_an_empty_symbol_is_refused():
    assert symbol_search.looks_unpriceable("   ")


# --- it must not fall over when the table is missing ------------------------


def test_a_missing_table_degrades_instead_of_raising(monkeypatch, tmp_path):
    """The data file not shipping must not 500 the page somebody is using to
    add a stock; shape-based guesses are a much better failure."""
    symbol_search._listings.cache_clear()
    monkeypatch.setattr(symbol_search, "_DATA", tmp_path / "nope.json")
    try:
        assert symbol_search._listings() == []
        assert search("2330") == [] or search("2330")[0].verified is False
        assert search("AAPL")[0].symbol == "AAPL"
    finally:
        symbol_search._listings.cache_clear()


# --- the endpoint -----------------------------------------------------------


def test_the_search_endpoint_answers_a_chinese_query(auth_client):
    body = auth_client.get("/api/symbols/search?q=%E5%8F%B0%E7%A9%8D%E9%9B%BB").json()

    assert body["matches"][0]["symbol"] == "2330.TW"
    assert body["listings_generated_at"]


def test_the_search_endpoint_answers_a_bare_code(auth_client):
    body = auth_client.get("/api/symbols/search?q=2330").json()

    assert body["matches"][0]["symbol"] == "2330.TW"


def test_an_empty_query_is_an_empty_list_not_an_error(auth_client):
    resp = auth_client.get("/api/symbols/search?q=")

    assert resp.status_code == 200
    assert resp.json()["matches"] == []


def test_the_search_endpoint_needs_a_login(client):
    assert client.get("/api/symbols/search?q=2330").status_code == 401


def test_the_watchlist_refuses_a_company_name_with_a_usable_message(auth_client):
    """The end of the owner's actual journey: typing 台積電 used to create a row
    that never priced. It now fails with the answer in the message."""
    resp = auth_client.post("/api/watchlist", json={"symbol": "台積電"})

    assert resp.status_code == 422
    assert "2330" in resp.text


def test_the_watchlist_refuses_a_bare_taiwanese_code(auth_client):
    resp = auth_client.post("/api/watchlist", json={"symbol": "2330"})

    assert resp.status_code == 422
    assert "2330.TW" in resp.text


def test_a_strategy_cannot_be_created_on_a_company_name_either(auth_client):
    resp = auth_client.post(
        "/api/strategies",
        json={
            "name": "x",
            "symbol": "台積電",
            "source_code": "class Strategy:\n    pass\n",
        },
    )

    assert resp.status_code == 422
