"""Typing 「台積電」 and ending up with a symbol that actually prices.

The owner's complaint, in their words: 「輸入欄位使用者不會知道要如何填，通常是打
台積電或2330這種代表性指標」. What the app needed was 2330.TW, and nothing
anywhere told anybody that.

Both of the things they would naturally type failed, and both failed quietly:

  「台積電」 was accepted by the watchlist, stored, and then asked for by every
  poll. Yahoo has no such symbol, so no price ever came back -- no row, no
  error, and no alert from an entry that looked correctly configured.

  「2330」 is worse. Yahoo resolves a bare 2330 to a Japanese OTC company, so it
  DOES price -- the wrong company's price, delivered with total confidence.
  For an alerting product that is the most dangerous outcome available.

The rule this module is built around: offer candidates, never substitute. A
watchlist silently pointing at the wrong company is worse than an input that
was refused.
"""

import pytest

from app.models.enums import DataSource
from app.services import symbol_search
from app.services.symbol_search import normalise, search


def _symbols(query: str) -> list[str]:
    return [match.symbol for match in search(query)]


# --- the bundled table is real ----------------------------------------------


def test_the_listings_table_is_actually_bundled():
    """Everything else here is meaningless if the data file did not ship. It
    is generated by scripts/refresh_tw_listings.py and committed on purpose --
    an app that has to reach TWSE before it can add a stock to a watchlist has
    acquired a runtime dependency it does not need."""
    rows = symbol_search._listings()

    assert len(rows) > 1500, f"only {len(rows)} listings; is app/data/tw_listings.json present?"
    assert symbol_search.listings_generated_at()


def test_both_boards_are_present():
    """上櫃 is not a rounding error -- 環球晶 and friends live there, and a table
    with only 上市 would reject them as unknown."""
    suffixes = {row["symbol"].split(".")[-1] for row in symbol_search._listings()}

    assert suffixes == {"TW", "TWO"}


# --- what the owner actually types ------------------------------------------


def test_the_chinese_name_finds_the_stock():
    """The whole reason a bundled table exists: Yahoo's search answers HTTP 400
    to any query containing Chinese."""
    assert "2330.TW" in _symbols("台積電")


def test_the_chinese_name_is_the_FIRST_result_not_the_ninth():
    """An exact short-name match buried under companies whose full name merely
    contains those characters makes the picker useless."""
    assert _symbols("台積電")[0] == "2330.TW"


def test_a_bare_code_offers_the_qualified_symbol():
    assert _symbols("2330")[0] == "2330.TW"


def test_an_otc_code_gets_the_TWO_suffix_not_TW():
    """Getting the board wrong produces a symbol that does not price at all,
    which at least fails loudly -- but it fails on the owner, at the moment
    they were trying to set up an alert."""
    assert _symbols("6488")[0] == "6488.TWO"


def test_an_already_correct_symbol_is_confirmed_with_its_company_name():
    """Confirming matters: a typo'd digit is still a perfectly well-formed
    symbol, and 2231.TW instead of 2330.TW would never announce itself."""
    matches = search("2330.TW")

    assert matches[0].symbol == "2330.TW"
    assert "台積電" in matches[0].name


def test_a_lowercase_suffix_is_understood():
    assert _symbols("2330.tw")[0] == "2330.TW"


def test_a_partial_chinese_name_still_finds_it():
    assert "2330.TW" in _symbols("台積")


def test_a_us_ticker_with_no_entry_is_offered_but_marked_as_unconfirmed():
    """Written with AAPL originally, when there was no US table at all and
    every US ticker was a guess from the shape of the input. AAPL is now in
    app/data/us_aliases.json and genuinely confirmed, so the case this test is
    about needs a ticker the table has never heard of. Saying "unconfirmed" is
    still the difference between a suggestion and a claim."""
    matches = search("ZZZZ")

    assert matches[0].symbol == "ZZZZ"
    assert matches[0].verified is False
    assert matches[0].data_source is DataSource.YFINANCE


def test_a_taiwanese_result_IS_confirmed():
    assert search("2330")[0].verified is True


def test_a_binance_pair_is_recognised_as_crypto():
    matches = search("BTCUSDT")

    assert matches[0].symbol == "BTCUSDT"
    assert matches[0].data_source is DataSource.BINANCE


def test_nonsense_returns_nothing_rather_than_a_plausible_guess():
    """An empty list is a real answer -- it means this app cannot price that --
    and it is what stops a watchlist row being created that never alerts."""
    assert search("這不是一支股票") == []


def test_an_empty_query_is_not_an_error():
    assert search("") == []
    assert search("   ") == []


def test_results_are_capped():
    """The picker is a dropdown on a phone, not a report."""
    assert len(search("科技", limit=5)) <= 5


# --- normalising what gets stored -------------------------------------------


@pytest.mark.parametrize("raw", ["aapl", " AAPL ", "AAPL", "  aapl  "])
def test_latin_symbols_normalise_to_one_stored_form(raw):
    """Three watchlist rows for the same stock is three separate polls and
    three separate alerts."""
    assert normalise(raw) == "AAPL"


def test_chinese_is_left_exactly_as_typed():
    """Upper-casing it would be meaningless, and any transformation here edges
    towards the guessing this module refuses to do."""
    assert normalise(" 台積電 ") == "台積電"


def test_a_taiwanese_symbol_normalises_its_suffix():
    assert normalise("2330.tw") == "2330.TW"


# --- refusing what can never work -------------------------------------------


def test_a_company_name_is_refused_with_the_answer_in_the_message():
    """The old behaviour accepted it and produced a row that never priced."""
    reason = symbol_search.looks_unpriceable("台積電")

    assert reason
    assert "2330" in reason


def test_a_bare_taiwanese_code_is_refused_and_the_reason_is_the_dangerous_one():
    """This is the one that would otherwise have worked, on the wrong company."""
    reason = symbol_search.looks_unpriceable("2330")

    assert reason
    assert "2330.TW" in reason


def test_a_bare_otc_code_is_told_about_TWO_specifically():
    reason = symbol_search.looks_unpriceable("6488")

    assert reason and "6488.TWO" in reason


@pytest.mark.parametrize("symbol", ["2330.TW", "6488.TWO", "AAPL", "BTCUSDT", "BRK-B"])
def test_things_that_can_price_are_left_alone(symbol):
    assert symbol_search.looks_unpriceable(symbol) is None


def test_an_unknown_us_ticker_is_still_allowed_through():
    """A whitelist would reject every newly listed company and every ticker the
    bundled table has never heard of. Being unable to add a stock is a worse
    failure than adding one that turns out not to price -- the latter shows up
    immediately as a missing quote."""
    assert symbol_search.looks_unpriceable("ZZZZ") is None


def test_an_empty_symbol_is_refused():
    assert symbol_search.looks_unpriceable("   ")


# --- it must not fall over when the table is missing ------------------------


def test_a_missing_table_degrades_instead_of_raising(monkeypatch, tmp_path):
    """The data file not shipping must not 500 the page somebody is using to
    add a stock; shape-based guesses are a much better failure."""
    symbol_search._listings.cache_clear()
    monkeypatch.setattr(symbol_search, "_DATA", tmp_path / "nope.json")
    try:
        assert symbol_search._listings() == []
        assert search("2330") == [] or search("2330")[0].verified is False
        assert search("AAPL")[0].symbol == "AAPL"
    finally:
        symbol_search._listings.cache_clear()


# --- the endpoint -----------------------------------------------------------


def test_the_search_endpoint_answers_a_chinese_query(auth_client):
    body = auth_client.get("/api/symbols/search?q=%E5%8F%B0%E7%A9%8D%E9%9B%BB").json()

    assert body["matches"][0]["symbol"] == "2330.TW"
    assert body["listings_generated_at"]


def test_the_search_endpoint_answers_a_bare_code(auth_client):
    body = auth_client.get("/api/symbols/search?q=2330").json()

    assert body["matches"][0]["symbol"] == "2330.TW"


def test_an_empty_query_is_an_empty_list_not_an_error(auth_client):
    resp = auth_client.get("/api/symbols/search?q=")

    assert resp.status_code == 200
    assert resp.json()["matches"] == []


def test_the_search_endpoint_needs_a_login(client):
    assert client.get("/api/symbols/search?q=2330").status_code == 401


def test_the_watchlist_refuses_a_company_name_with_a_usable_message(auth_client):
    """The end of the owner's actual journey: typing 台積電 used to create a row
    that never priced. It now fails with the answer in the message."""
    resp = auth_client.post("/api/watchlist", json={"symbol": "台積電"})

    assert resp.status_code == 422
    assert "2330" in resp.text


def test_the_watchlist_refuses_a_bare_taiwanese_code(auth_client):
    resp = auth_client.post("/api/watchlist", json={"symbol": "2330"})

    assert resp.status_code == 422
    assert "2330.TW" in resp.text


def test_a_strategy_cannot_be_created_on_a_company_name_either(auth_client):
    resp = auth_client.post(
        "/api/strategies",
        json={
            "name": "x",
            "symbol": "台積電",
            "source_code": "class Strategy:\n    pass\n",
        },
    )

    assert resp.status_code == 422


# --- US stocks by the name a Taiwanese investor uses ------------------------
#
# The TW registry comes from the exchanges' own data. For US listings there is
# no equivalent to fetch: Yahoo's search answers HTTP 400 to any query with
# Chinese in it, and its quote endpoint answers 401 without a crumb. So 「輝達」
# and 「蘋果」 -- which is how the owner thinks of these companies -- returned
# nothing at all, and the only way in was to already know the ticker.
#
# app/data/us_aliases.json is a hand-curated list, but nothing ships on that
# assertion alone: scripts/refresh_us_aliases.py fetches every ticker and writes
# the PROVIDER'S OWN name into the file, so a wrong entry is visible in review
# and the owner always chooses against a name the price feed supplied.


def test_a_chinese_name_finds_a_us_stock():
    assert "NVDA" in _symbols("輝達")


def test_both_names_in_daily_use_work():
    """「輝達」 and 「英偉達」 are both current. Picking one would leave the other
    person with nothing, which is the failure this whole feature is about."""
    assert "NVDA" in _symbols("輝達")
    assert "NVDA" in _symbols("英偉達")


def test_the_result_carries_the_name_the_price_feed_gave():
    """The owner has to be choosing against something the provider said, not
    against a claim this repo makes about what 輝達 means.

    It sits in `name`, the same slot the Taiwanese rows put 台積電 in, so a list
    containing both reads as one list rather than two shapes."""
    match = next(m for m in search("輝達") if m.symbol == "NVDA")

    assert "NVIDIA" in match.name, match.name


def test_a_us_alias_result_is_marked_verified():
    """Unlike a bare ticker guessed from its shape, this one was checked
    against the live feed when the table was built."""
    match = next(m for m in search("蘋果") if m.symbol == "AAPL")

    assert match.verified is True
    assert match.market == symbol_search.MARKET_US


def test_a_ticker_in_the_table_is_now_confirmed_rather_than_guessed():
    """AAPL used to come back as an unverified shape-based guess. It is in the
    table, so the app can say which company it is."""
    match = search("AAPL")[0]

    assert match.symbol == "AAPL"
    assert match.verified is True
    assert "Apple" in match.name


def test_a_ticker_outside_the_table_is_still_offered_but_unconfirmed():
    """The table is deliberately small -- what people actually search for, not
    the whole US market. Everything else must still work by ticker."""
    match = search("ZZZZ")[0]

    assert match.symbol == "ZZZZ"
    assert match.verified is False


def test_the_taiwanese_line_and_the_us_adr_are_both_offered_and_distinguishable():
    """2317.TW is 246 TWD and HNHPF is 15 USD; both are Hon Hai and both price.
    Where the app knows of two, it must show both with their markets rather
    than pick -- 「台積電ADR」 is a different instrument from 台積電."""
    tw = next(m for m in search("台積電") if m.symbol == "2330.TW")
    us = next(m for m in search("台積電ADR") if m.symbol == "TSM")

    assert tw.market == symbol_search.MARKET_TW
    assert us.market == symbol_search.MARKET_US


def test_a_taiwanese_name_does_not_get_buried_under_us_aliases():
    """台積電 is a Taiwanese company first. Ordering matters more than
    completeness in a dropdown somebody reads on a phone."""
    assert _symbols("台積電")[0] == "2330.TW"


def test_the_us_table_is_actually_bundled():
    entries = symbol_search._us_aliases()

    assert len(entries) > 40, f"only {len(entries)}; is app/data/us_aliases.json present?"
    assert all(e.get("name") for e in entries), "every entry must carry the fetched name"


def test_a_missing_us_table_degrades_instead_of_raising(monkeypatch, tmp_path):
    symbol_search._us_aliases.cache_clear()
    monkeypatch.setattr(symbol_search, "_US_DATA", tmp_path / "nope.json")
    try:
        assert symbol_search._us_aliases() == []
        assert search("AAPL")[0].symbol == "AAPL"
    finally:
        symbol_search._us_aliases.cache_clear()


# --- ETFs whose code carries a board letter ---------------------------------
#
# The ETF filter was written as ^00\d{2,4}$, which silently dropped 94 tradable
# TWSE codes -- among them 元大台灣50正2 (00631L) and 元大台灣50反1 (00632R), two
# of the most traded ETFs in Taiwan, and all ten 主動式 ETFs launched in 2025
# (00400A-00410A).
#
# The compounding part is what made it dangerous rather than merely incomplete:
# search() found nothing AND looks_unpriceable() waved the bare code through,
# so the app accepted 00632R, stored it, and could never price it. A watchlist
# row that looks perfectly healthy and never fires -- exactly what this module's
# docstring says it exists to prevent.


def test_a_leveraged_etf_is_in_the_table():
    assert _symbols("00631L")[0] == "00631L.TW"


def test_an_inverse_etf_is_in_the_table():
    assert _symbols("00632R")[0] == "00632R.TW"


def test_the_active_etfs_are_in_the_table():
    """Ten of these listed in 2025 and the filter dropped every one."""
    assert _symbols("00400A")[0] == "00400A.TW"


def test_a_lettered_code_is_no_longer_waved_through_unpriceable():
    """The bare form cannot price. Returning None here is what let it become a
    watchlist row that never alerts."""
    reason = symbol_search.looks_unpriceable("00632R")

    assert reason
    assert "00632R.TW" in reason, reason


def test_the_qualified_lettered_symbol_is_accepted():
    assert symbol_search.looks_unpriceable("00632R.TW") is None


def test_a_lettered_code_normalises_and_resolves_from_a_webhook():
    """{{ticker}} on a TWSE:00632R chart sends 「00632R」."""
    symbol, note = symbol_search.resolve_incoming("00632r")

    assert symbol == "00632R.TW"
    assert note


# --- the same company on two markets ----------------------------------------
#
# 「台積電」 was a registry hit, so search() answered 2330.TW and stopped -- the
# US ADR never appeared at all. That made the one ambiguity that matters
# unreachable rather than resolved: somebody holding TSM types the company's
# name, gets the Taiwanese line, and sets 「跌破 220」 meaning US$220 against a
# NT$2,375 stock. It never fires. Once. Ever. And the row looks healthy.
#
# So both are offered, each labelled with its market AND its currency -- the
# two facts that tell them apart, since the provider's own name for both is
# 「Taiwan Semiconductor Manufacturing」.


def test_a_taiwanese_company_with_an_adr_offers_both():
    symbols = _symbols("台積電")

    assert "2330.TW" in symbols
    assert "TSM" in symbols


def test_the_taiwanese_line_comes_first():
    """台積電 is a Taiwanese company. The ADR is the alternative, not the
    default, and a dropdown read on a phone is decided by what is on top."""
    assert _symbols("台積電")[0] == "2330.TW"


def test_each_carries_its_own_currency():
    """The disambiguator. Both are named 「台積電」 and both price; only the
    currency says that 220 means two different things."""
    tw = next(m for m in search("台積電") if m.symbol == "2330.TW")
    adr = next(m for m in search("台積電") if m.symbol == "TSM")

    assert tw.currency == "TWD"
    assert adr.currency == "USD"


def test_the_adr_row_says_it_is_an_adr():
    """「美股」 alone does not explain why the same company is listed twice."""
    adr = next(m for m in search("台積電") if m.symbol == "TSM")

    assert "ADR" in adr.detail


def test_the_other_adr_pairs_work_too():
    for query, tw_symbol, adr in [
        ("聯電", "2303.TW", "UMC"),
        ("日月光投控", "3711.TW", "ASX"),
        ("中華電", "2412.TW", "CHT"),
    ]:
        symbols = _symbols(query)
        assert tw_symbol in symbols, query
        assert adr in symbols, query


def test_a_company_with_no_adr_is_not_given_one():
    symbols = _symbols("環球晶")

    assert symbols == ["6488.TWO"]


def test_every_result_carries_a_currency():
    """A row without one is a row the picker cannot label, which is how the
    ambiguity got through in the first place."""
    for query in ["台積電", "2330", "AAPL", "輝達", "BTCUSDT"]:
        for match in search(query):
            assert match.currency, f"{query} -> {match.symbol} has no currency"
