"""A deployment that has not been configured yet must still be able to say so.

The app refuses to start when a signing secret is missing, at IMPORT time, on
purpose -- see config.enforce_required_secrets. That rule is right and stays:
serving the real API with a forgeable JWT_SECRET is worse than not serving.

But it produces the wrong outcome for the audience this repo is built for. The
README hands a stranger two deploy buttons; render.yaml then asks them for
seven values, and two of those (`SECRET_ENCRYPTION_KEY`, the VAPID pair) are
generated by running a Python script on their own machine. Somebody who wants
stock alerts on their phone does not have Python. They leave the blanks empty,
Render builds, the process dies at import, and what they get is a 502 and a
stack trace in a log they will not find.

The one thing they need at that moment -- what is missing, why, and a button
that produces the value -- is exactly what a dead process cannot serve.

SO THERE ARE TWO MODES, AND THEY ARE MUTUALLY EXCLUSIVE.

  Configured: the app as it has always been. The setup endpoints do not exist.
  Not configured: the app serves the setup endpoints and NOTHING ELSE. Every
    real route answers 503. No login is possible, no token is minted, no worker
    runs, no database is touched.

The security property the import-time guard was defending is therefore intact:
with a missing or weak JWT_SECRET there is still no route that would accept or
issue one. What changed is that the process stays up long enough to explain
itself.

WHAT THE SETUP ENDPOINTS MUST NEVER DO: echo a value that is already set.
「missing or present」 is the whole of what they report. Generating a fresh
random key gives an attacker nothing they could not generate themselves, and
nothing is written anywhere -- the human copies the value into Render.
"""

import pytest

from app.config import Settings
from app.services import setup_state

# A configuration with every blocking value filled in, so a test about ONE
# missing setting is only about that one.
_COMPLETE = {
    "JWT_SECRET": "a" * 48,
    "TV_WEBHOOK_SECRET": "b" * 48,
    "SECRET_ENCRYPTION_KEY": "",  # filled in per-test with a real Fernet key
    "DATABASE_URL": "postgresql://user:pw@host/db",
}


def _fernet_key() -> str:
    from cryptography.fernet import Fernet

    return Fernet.generate_key().decode()


def _settings(**overrides) -> Settings:
    values = {**_COMPLETE, "SECRET_ENCRYPTION_KEY": _fernet_key()}
    values.update(overrides)
    return Settings(**values)


def _names(s: Settings) -> list[str]:
    return [item.name for item in setup_state.missing_settings(s)]


# --- what counts as configured ----------------------------------------------


def test_a_fully_configured_deployment_needs_no_setup():
    assert setup_state.is_configured(_settings())
    assert setup_state.missing_settings(_settings()) == []


def test_the_encryption_key_is_the_wall_a_one_click_deploy_hits():
    """render.yaml leaves it blank and tells the deployer to run a Python
    script. This is the value that kills the process at import."""
    assert "SECRET_ENCRYPTION_KEY" in _names(_settings(SECRET_ENCRYPTION_KEY=""))


def test_a_malformed_encryption_key_counts_as_missing():
    """Present enough for a truthiness check, wrong enough to fail the first
    time a secret is saved. config._verify_encryption_key already refuses it;
    setup has to agree, or the page would report 「done」 about a boot that
    still crashes."""
    assert "SECRET_ENCRYPTION_KEY" in _names(_settings(SECRET_ENCRYPTION_KEY="not-a-fernet-key"))


def test_an_unset_signing_secret_is_reported():
    assert "JWT_SECRET" in _names(_settings(JWT_SECRET=""))


def test_a_placeholder_signing_secret_is_reported_too():
    assert "JWT_SECRET" in _names(_settings(JWT_SECRET="change-me"))


def test_the_dev_sqlite_default_is_not_a_deployment_database():
    """The default is a local file. On Render that file lives on a disk that
    is wiped on every deploy, so a deployment left on it loses every account,
    strategy and alert without a word."""
    assert "DATABASE_URL" in _names(_settings(DATABASE_URL="sqlite:///./trading_app_dev.db"))


def test_a_real_database_url_is_accepted():
    assert "DATABASE_URL" not in _names(_settings())


# --- web push is optional, and saying otherwise would be a lie --------------


def test_no_vapid_at_all_is_a_valid_deployment():
    """config._verify_vapid says so explicitly: web push is one channel of
    four, and somebody using only Telegram and email must not be blocked."""
    settings = _settings(VAPID_PUBLIC_KEY="", VAPID_PRIVATE_KEY="")

    assert setup_state.is_configured(settings)


def test_half_a_vapid_pair_is_reported():
    """Half a pair can only be a mistake, and it produces a silent 403 on
    every push."""
    assert "VAPID_PRIVATE_KEY" in _names(_settings(VAPID_PUBLIC_KEY="something"))


# --- every entry has to be actionable ---------------------------------------


def test_each_missing_setting_says_what_breaks_without_it():
    for item in setup_state.missing_settings(_settings(SECRET_ENCRYPTION_KEY="")):
        assert item.why.strip(), item


def test_each_missing_setting_says_where_to_get_it():
    for item in setup_state.missing_settings(_settings(SECRET_ENCRYPTION_KEY="")):
        assert item.how.strip(), item


def test_the_ones_the_app_can_produce_itself_say_so():
    """The whole point of this exercise. A value the app can generate must not
    send somebody to install Python."""
    item = next(
        i for i in setup_state.missing_settings(_settings(SECRET_ENCRYPTION_KEY="")) if i.generator
    )

    assert item.generator == "fernet"


def test_the_database_url_is_honest_that_nobody_can_generate_it():
    """It is somebody else's service. Offering a button would be a lie."""
    item = next(
        i
        for i in setup_state.missing_settings(_settings(DATABASE_URL=""))
        if i.name == "DATABASE_URL"
    )

    assert item.generator is None


# --- the generators ----------------------------------------------------------


def test_a_generated_fernet_key_is_one_the_app_would_accept():
    """Round-tripped through the very check that refuses the boot, so the
    button cannot hand somebody a value that still fails."""
    from cryptography.fernet import Fernet

    generated = setup_state.generate("fernet")

    Fernet(generated["SECRET_ENCRYPTION_KEY"].encode())


def test_a_generated_vapid_pair_matches_itself():
    """A mismatched pair is the failure this app already refuses to boot on --
    generating one would be an own goal."""
    from app.config import Settings as S
    from app.config import _verify_vapid

    generated = setup_state.generate("vapid")

    _verify_vapid(
        S(
            VAPID_PUBLIC_KEY=generated["VAPID_PUBLIC_KEY"],
            VAPID_PRIVATE_KEY=generated["VAPID_PRIVATE_KEY"],
            VAPID_SUBJECT="mailto:owner@example.com",
        )
    )


def test_a_generated_signing_secret_is_long_enough_not_to_be_guessed():
    assert len(setup_state.generate("token")["value"]) >= 32


def test_two_generated_values_are_not_the_same_value():
    assert setup_state.generate("token") != setup_state.generate("token")


def test_an_unknown_generator_is_refused_rather_than_improvised():
    with pytest.raises(ValueError):
        setup_state.generate("something-else")


# --- and it never reveals what is already there ------------------------------


def test_a_configured_value_is_never_echoed_back():
    """These endpoints are unauthenticated by necessity -- there is no login
    before there is a JWT_SECRET. Reporting 「missing or present」 is safe;
    reporting the value is handing over the deployment."""
    secret = "s" * 48
    settings = _settings(JWT_SECRET=secret, SECRET_ENCRYPTION_KEY="")

    rendered = repr(setup_state.missing_settings(settings))

    assert secret not in rendered


# --- the endpoints ------------------------------------------------------------


def _unconfigure(monkeypatch):
    """Make this process look like a fresh deploy with the blank Render leaves."""
    monkeypatch.setattr("app.config.settings.SECRET_ENCRYPTION_KEY", "")


def test_the_status_endpoint_lists_what_is_missing(client, monkeypatch):
    _unconfigure(monkeypatch)

    body = client.get("/api/setup/status").json()

    assert "SECRET_ENCRYPTION_KEY" in [item["name"] for item in body["missing"]]


def test_the_status_endpoint_says_where_to_paste_the_answers(client, monkeypatch):
    """The whole audience for this page has just met Render for the first time
    and does not know env vars live under Settings -> Environment."""
    _unconfigure(monkeypatch)

    assert "Environment" in client.get("/api/setup/status").json()["where"]


def test_the_endpoints_disappear_once_there_is_nothing_to_configure(client, monkeypatch):
    """404 rather than 403: there is nothing here to be forbidden from, and a
    route that exists but refuses invites somebody to keep knocking."""
    monkeypatch.setattr("app.config.settings.SECRET_ENCRYPTION_KEY", _fernet_key())
    monkeypatch.setattr("app.config.settings.DATABASE_URL", "postgresql://u:p@h/d")
    monkeypatch.setattr("app.config.settings.JWT_SECRET", "j" * 48)
    monkeypatch.setattr("app.config.settings.TV_WEBHOOK_SECRET", "t" * 48)
    monkeypatch.setattr("app.config.settings.VAPID_PUBLIC_KEY", "")
    monkeypatch.setattr("app.config.settings.VAPID_PRIVATE_KEY", "")

    assert client.get("/api/setup/status").status_code == 404


def test_generate_hands_back_a_usable_key(client, monkeypatch):
    _unconfigure(monkeypatch)

    body = client.post("/api/setup/generate", json={"kind": "fernet"}).json()

    from cryptography.fernet import Fernet

    Fernet(body["SECRET_ENCRYPTION_KEY"].encode())


def test_generate_refuses_a_kind_it_does_not_know(client, monkeypatch):
    _unconfigure(monkeypatch)

    assert client.post("/api/setup/generate", json={"kind": "rm -rf"}).status_code == 422


def test_the_setup_endpoints_need_no_login(client, monkeypatch):
    """There is no login before there is a JWT_SECRET. `client` carries no
    token, unlike `auth_client`."""
    _unconfigure(monkeypatch)

    assert client.get("/api/setup/status").status_code == 200


# --- the lockdown ---------------------------------------------------------------


def _setup_mode(monkeypatch):
    monkeypatch.setattr("app.main.SETUP_MODE_REASON", "SECRET_ENCRYPTION_KEY is unset")
    monkeypatch.setattr("app.config.settings.SECRET_ENCRYPTION_KEY", "")


def test_every_real_route_is_shut_while_unconfigured(auth_client, monkeypatch):
    """Not 404 and not a crash: a plain 503 saying why, so the frontend can
    send the person to the setup page rather than showing them a blank
    dashboard."""
    _setup_mode(monkeypatch)

    resp = auth_client.get("/api/positions")

    assert resp.status_code == 503
    assert resp.json()["setup_required"] is True


def test_logging_in_is_not_possible_while_unconfigured(client, monkeypatch):
    """The property the old crash was defending. A weak JWT_SECRET must never
    mint a token, and the way to guarantee that is for no route to exist that
    could."""
    _setup_mode(monkeypatch)

    resp = client.post("/api/auth/login", data={"username": "a@b.c", "password": "x"})

    assert resp.status_code == 503


def test_the_setup_endpoints_still_answer(client, monkeypatch):
    _setup_mode(monkeypatch)

    assert client.get("/api/setup/status").status_code == 200


def test_the_health_probe_still_answers_and_says_it_is_unconfigured(client, monkeypatch):
    """The external watchdog is the only thing watching an unconfigured
    deployment. Answered without touching the database, because a missing
    DATABASE_URL is one of the things being reported -- a probe that 500s on
    the way to saying 「not configured」 says nothing."""
    _setup_mode(monkeypatch)

    resp = client.get("/healthz")

    assert resp.status_code == 503
    assert resp.json()["checks"]["setup"]["status"] == "fail"


def test_nothing_is_locked_once_the_deployment_is_configured(auth_client):
    """The default state of this suite, asserted rather than assumed: the
    middleware must be inert for everybody who has finished setting up."""
    assert auth_client.get("/api/positions").status_code == 200
