"""add alert-only strategies

Revision ID: 07b3c25465f6
Revises: 1e5c5c7819b8
Create Date: 2026-08-18 10:41:12.475129

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '07b3c25465f6'
down_revision: str | Sequence[str] | None = '1e5c5c7819b8'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strategy_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('side', sa.Enum('BUY', 'SELL', name='orderside', native_enum=False, length=8), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('status', sa.Enum('SENT', 'FAILED', name='notificationstatus', native_enum=False, length=16), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], name=op.f('fk_strategy_alerts_strategy_id_strategies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_strategy_alerts_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_strategy_alerts'))
    )
    with op.batch_alter_table('strategy_alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_strategy_alerts_strategy_id'), ['strategy_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_strategy_alerts_user_id'), ['user_id'], unique=False)

    # server_default (not in the models, which only carry the Python-side
    # default) is what backfills the rows already in the table: every existing
    # strategy stays order-creating, and every existing user gets the same
    # alert interval a new one would. Without it these NOT NULL columns cannot
    # be added to a non-empty table at all.
    with op.batch_alter_table('risk_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('alert_interval_sec', sa.Integer(), nullable=False, server_default='900'))

    with op.batch_alter_table('strategies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('alert_only', sa.Boolean(), nullable=False, server_default=sa.false()))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('strategies', schema=None) as batch_op:
        batch_op.drop_column('alert_only')

    with op.batch_alter_table('risk_settings', schema=None) as batch_op:
        batch_op.drop_column('alert_interval_sec')

    with op.batch_alter_table('strategy_alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_strategy_alerts_user_id'))
        batch_op.drop_index(batch_op.f('ix_strategy_alerts_strategy_id'))

    op.drop_table('strategy_alerts')
    # ### end Alembic commands ###
