"""strategy versions: a way back from an edit that broke it

Revision ID: 09da5bd6bc45
Revises: 4a364025b866
Create Date: 2026-08-28 02:21:00.840574

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "09da5bd6bc45"
down_revision: str | Sequence[str] | None = "4a364025b866"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "strategy_versions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("strategy_id", sa.Integer(), nullable=False),
        sa.Column("source_code", sa.Text(), nullable=False),
        sa.Column("params", sa.JSON(), nullable=False),
        sa.Column("code_hash", sa.String(length=64), nullable=False),
        sa.Column("author", sa.String(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["strategy_id"],
            ["strategies.id"],
            name=op.f("fk_strategy_versions_strategy_id_strategies"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_strategy_versions")),
    )
    with op.batch_alter_table("strategy_versions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_strategy_versions_strategy_id"), ["strategy_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("strategy_versions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_strategy_versions_strategy_id"))

    op.drop_table("strategy_versions")
    # ### end Alembic commands ###
