"""record what actually filled on an order

Revision ID: 0cc4c440f39a
Revises: 5ea414842b36
Create Date: 2026-08-19 12:05:36.409193

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0cc4c440f39a"
down_revision: str | Sequence[str] | None = "5ea414842b36"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("filled_quantity", sa.Numeric(precision=18, scale=8), nullable=True)
        )

    # Every confirmation the app has ever accepted filled the whole order --
    # the partial-fill path is new in this same change. Leaving these NULL
    # would read as "nothing filled" and hand every existing strategy back
    # capital it is actually still holding.
    op.execute(
        sa.text(
            "UPDATE orders SET filled_quantity = quantity "
            "WHERE status = 'CONFIRMED' AND filled_quantity IS NULL"
        )
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.drop_column("filled_quantity")

    # ### end Alembic commands ###
