"""email an encrypted backup on a timer

Revision ID: 26b102a6ef79
Revises: b15885cd9bba
Create Date: 2026-08-19 21:20:23.443912

"""

from collections.abc import Sequence

import sqlalchemy as sa

import app.db.types
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "26b102a6ef79"
down_revision: str | Sequence[str] | None = "b15885cd9bba"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "backup_schedules",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("is_enabled", sa.Boolean(), nullable=False),
        sa.Column("interval_days", sa.Integer(), nullable=False),
        sa.Column("passphrase_encrypted", app.db.types.EncryptedJSON(), nullable=True),
        sa.Column("to_addr", sa.String(length=255), nullable=True),
        sa.Column("last_sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_backup_schedules_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_backup_schedules")),
    )
    with op.batch_alter_table("backup_schedules", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_backup_schedules_user_id"), ["user_id"], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("backup_schedules", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_backup_schedules_user_id"))

    op.drop_table("backup_schedules")
    # ### end Alembic commands ###
