"""keep a channels failure record when the channel is deleted

Revision ID: 375f6250d1b8
Revises: a4de890b62dd
Create Date: 2026-08-20 15:09:03.757515

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "375f6250d1b8"
down_revision: str | Sequence[str] | None = "a4de890b62dd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("notification_logs", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_notification_logs_channel_id_notification_channels"), type_="foreignkey"
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_notification_logs_channel_id_notification_channels"),
            "notification_channels",
            ["channel_id"],
            ["id"],
            ondelete="SET NULL",
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("notification_logs", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_notification_logs_channel_id_notification_channels"), type_="foreignkey"
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_notification_logs_channel_id_notification_channels"),
            "notification_channels",
            ["channel_id"],
            ["id"],
            ondelete="CASCADE",
        )

    # ### end Alembic commands ###
