"""per-strategy risk overrides

Revision ID: 3883a0878a24
Revises: 07b3c25465f6
Create Date: 2026-08-18 15:43:20.499203

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '3883a0878a24'
down_revision: str | Sequence[str] | None = '07b3c25465f6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Every column here is nullable with no server_default, and that is the
    # feature rather than an oversight: NULL is what "inherit the global
    # RiskSettings value" is spelled as (services/risk_resolver.py). Existing
    # rows therefore come out inheriting, which is exactly how they behaved
    # before these columns existed. A server_default would opt every strategy
    # the owner already has into an override nobody asked for.
    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('strategy_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_positions_strategy_id_strategies'), 'strategies', ['strategy_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('strategies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('capital', sa.Numeric(precision=18, scale=8), nullable=True))
        batch_op.add_column(sa.Column('stop_loss_pct', sa.Numeric(precision=9, scale=6), nullable=True))
        batch_op.add_column(sa.Column('take_profit_pct', sa.Numeric(precision=9, scale=6), nullable=True))
        batch_op.add_column(sa.Column('max_position_qty', sa.Numeric(precision=18, scale=8), nullable=True))
        batch_op.add_column(sa.Column('max_order_notional', sa.Numeric(precision=18, scale=8), nullable=True))
        batch_op.add_column(sa.Column('max_pending_orders_per_symbol', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('signal_cooldown_sec', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('alert_interval_sec', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('strategies', schema=None) as batch_op:
        batch_op.drop_column('alert_interval_sec')
        batch_op.drop_column('signal_cooldown_sec')
        batch_op.drop_column('max_pending_orders_per_symbol')
        batch_op.drop_column('max_order_notional')
        batch_op.drop_column('max_position_qty')
        batch_op.drop_column('take_profit_pct')
        batch_op.drop_column('stop_loss_pct')
        batch_op.drop_column('capital')

    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_positions_strategy_id_strategies'), type_='foreignkey')
        batch_op.drop_column('strategy_id')

    # ### end Alembic commands ###
