"""push receipt token so a device can confirm it displayed the alert

Revision ID: 47c590667e49
Revises: fbbbbc022afd
Create Date: 2026-08-20 13:56:53.568814

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "47c590667e49"
down_revision: str | Sequence[str] | None = "fbbbbc022afd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("notification_logs", schema=None) as batch_op:
        batch_op.add_column(sa.Column("receipt_token", sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_notification_logs_receipt_token"), ["receipt_token"], unique=True
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("notification_logs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_notification_logs_receipt_token"))
        batch_op.drop_column("delivered_at")
        batch_op.drop_column("receipt_token")

    # ### end Alembic commands ###
