"""strategy: remember the version it last compiled under

Revision ID: 4a364025b866
Revises: 88b3163cb3cb
Create Date: 2026-08-27 12:14:22.922386

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4a364025b866"
down_revision: str | Sequence[str] | None = "88b3163cb3cb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("strategies", schema=None) as batch_op:
        batch_op.add_column(sa.Column("last_compiled_version", sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("strategies", schema=None) as batch_op:
        batch_op.drop_column("last_compiled_version")

    # ### end Alembic commands ###
