"""add backtest runs table

Revision ID: 5ea414842b36
Revises: 3883a0878a24
Create Date: 2026-08-18 17:57:50.557747

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5ea414842b36"
down_revision: str | Sequence[str] | None = "3883a0878a24"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # A completed backtest, kept so its numbers can be revisited. Every column
    # here is NOT NULL and there is no server_default anywhere, which is safe
    # precisely because the table starts empty: a run is only ever written in
    # one place (api/routers/backtests.py) and always in full. strategy_id is
    # the single exception -- NULL means the strategy it scored has since been
    # deleted, and the run stays readable from its own source_code snapshot.
    op.create_table(
        "backtest_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("strategy_id", sa.Integer(), nullable=True),
        sa.Column("strategy_name", sa.String(length=120), nullable=False),
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column("timeframe", sa.String(length=8), nullable=False),
        sa.Column(
            "data_source",
            sa.Enum("YFINANCE", "BINANCE", name="datasource", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("range_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("range_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source_code", sa.Text(), nullable=False),
        sa.Column("code_hash", sa.String(length=64), nullable=False),
        sa.Column("assumptions", sa.JSON(), nullable=False),
        sa.Column("summary", sa.JSON(), nullable=False),
        sa.Column("result", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["strategy_id"],
            ["strategies.id"],
            name=op.f("fk_backtest_runs_strategy_id_strategies"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_backtest_runs_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_backtest_runs")),
    )
    with op.batch_alter_table("backtest_runs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_backtest_runs_strategy_id"), ["strategy_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_backtest_runs_user_id"), ["user_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("backtest_runs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_backtest_runs_user_id"))
        batch_op.drop_index(batch_op.f("ix_backtest_runs_strategy_id"))

    op.drop_table("backtest_runs")
    # ### end Alembic commands ###
