"""record why a strategy signal was refused

Revision ID: 9e1c67c235ba
Revises: f5d5b2ce6b3d
Create Date: 2026-08-19 14:33:33.401308

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9e1c67c235ba"
down_revision: str | Sequence[str] | None = "f5d5b2ce6b3d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("strategies", schema=None) as batch_op:
        batch_op.add_column(sa.Column("last_blocked_reason", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("last_blocked_at", sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("strategies", schema=None) as batch_op:
        batch_op.drop_column("last_blocked_at")
        batch_op.drop_column("last_blocked_reason")

    # ### end Alembic commands ###
