"""a notification log row can belong to no channel at all

Revision ID: a4de890b62dd
Revises: 47c590667e49
Create Date: 2026-08-20 14:46:26.492181

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a4de890b62dd"
down_revision: str | Sequence[str] | None = "47c590667e49"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("notification_logs", schema=None) as batch_op:
        batch_op.alter_column("channel_id", existing_type=sa.INTEGER(), nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("notification_logs", schema=None) as batch_op:
        batch_op.alter_column("channel_id", existing_type=sa.INTEGER(), nullable=False)

    # ### end Alembic commands ###
