"""record which currency a quoted price is in

Revision ID: a5c92df44199
Revises: b9b0cf0fa4b7
Create Date: 2026-08-20 21:31:08.327249

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a5c92df44199"
down_revision: str | Sequence[str] | None = "b9b0cf0fa4b7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("market_quotes", schema=None) as batch_op:
        batch_op.add_column(sa.Column("currency", sa.String(length=8), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("market_quotes", schema=None) as batch_op:
        batch_op.drop_column("currency")

    # ### end Alembic commands ###
