"""watchlist belongs to the account not the browser

Revision ID: b15885cd9bba
Revises: d109305e96f8
Create Date: 2026-08-19 19:06:58.128390

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b15885cd9bba"
down_revision: str | Sequence[str] | None = "d109305e96f8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "watchlist_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column(
            "data_source",
            sa.Enum("YFINANCE", "BINANCE", name="datasource", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_watchlist_items_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_watchlist_items")),
        sa.UniqueConstraint("user_id", "symbol", name="uq_watchlist_user_symbol"),
    )
    with op.batch_alter_table("watchlist_items", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_watchlist_items_user_id"), ["user_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("watchlist_items", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_watchlist_items_user_id"))

    op.drop_table("watchlist_items")
    # ### end Alembic commands ###
