"""record when a webhook symbol had to be canonicalised

Revision ID: b9b0cf0fa4b7
Revises: 375f6250d1b8
Create Date: 2026-08-20 18:07:19.338853

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b9b0cf0fa4b7"
down_revision: str | Sequence[str] | None = "375f6250d1b8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tradingview_webhook_logs", schema=None) as batch_op:
        batch_op.add_column(sa.Column("note", sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tradingview_webhook_logs", schema=None) as batch_op:
        batch_op.drop_column("note")

    # ### end Alembic commands ###
