"""revocable tokens and a login record

Revision ID: c4ee0993ef5e
Revises: 26b102a6ef79
Create Date: 2026-08-19 21:43:12.155164

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c4ee0993ef5e"
down_revision: str | Sequence[str] | None = "26b102a6ef79"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    with op.batch_alter_table("users", schema=None) as batch_op:
        # server_default, because autogenerate wrote this NOT NULL with nothing
        # to fill it -- which fails against a users table that already has
        # rows. 0 is where every account starts, and is also what a token
        # issued before the `ver` claim existed decodes as, so this migration
        # signs nobody out.
        batch_op.add_column(
            sa.Column("token_version", sa.Integer(), nullable=False, server_default="0")
        )
        batch_op.add_column(sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(
            sa.Column("previous_login_at", sa.DateTime(timezone=True), nullable=True)
        )

    # Dropped once the backfill has happened: the application always supplies
    # the value, and a database-side default invites an insert that relies on
    # it silently.
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column("token_version", server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("previous_login_at")
        batch_op.drop_column("last_login_at")
        batch_op.drop_column("token_version")

    # ### end Alembic commands ###
