"""quiet hours per channel and a timezone per person

Revision ID: d109305e96f8
Revises: 173b1defdee1
Create Date: 2026-08-19 18:51:08.774690

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d109305e96f8"
down_revision: str | Sequence[str] | None = "173b1defdee1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("notification_channels", schema=None) as batch_op:
        batch_op.add_column(sa.Column("quiet_start_hour", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("quiet_end_hour", sa.Integer(), nullable=True))

    with op.batch_alter_table("users", schema=None) as batch_op:
        # server_default, not just a Python-side default: autogenerate wrote
        # this NOT NULL with nothing to backfill, which fails outright against
        # a users table that already has rows -- and the live one certainly
        # does. Taipei because that is where this deployment's owner is; a
        # second person elsewhere changes it on their account.
        batch_op.add_column(
            sa.Column(
                "timezone",
                sa.String(length=64),
                nullable=False,
                server_default="Asia/Taipei",
            )
        )

    # Dropped once the backfill has happened: the application always supplies
    # the value, and a database-side default invites a future insert that
    # silently relies on it.
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column("timezone", server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("timezone")

    with op.batch_alter_table("notification_channels", schema=None) as batch_op:
        batch_op.drop_column("quiet_end_hour")
        batch_op.drop_column("quiet_start_hour")

    # ### end Alembic commands ###
