"""give every timestamp column its timezone

Ten columns were declared as a bare `Mapped[datetime]`, which is TIMESTAMP
WITHOUT TIME ZONE. Every one of them stores `utcnow()`, so Postgres was
dropping the offset on write and handing back a naive value, which the API
then serialized with no offset at all. The browser reads an offset-less
timestamp as *local* time, so a position opened 09:30 in Taipei rendered as
01:30 -- eight hours early, and only on the pages whose columns happened to be
declared this way, which is what made it look like the clock was jumping
rather than like a type declaration being wrong.

Written by hand rather than autogenerated: this migration was developed
against SQLite, whose DATETIME has no timezone concept, so autogenerate saw
no difference and produced an empty upgrade. Postgres is the only backend
where the distinction is real, hence the dialect guard.

The stored values really are UTC, so `AT TIME ZONE 'UTC'` is the correct
reading of them -- it labels them rather than shifting them.

Revision ID: f5d5b2ce6b3d
Revises: 0cc4c440f39a
Create Date: 2026-08-19 14:22:06.728369

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f5d5b2ce6b3d"
down_revision: str | Sequence[str] | None = "0cc4c440f39a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


_COLUMNS: tuple[tuple[str, str], ...] = (
    ("market_quotes", "quote_time"),
    ("market_quotes", "fetched_at"),
    ("notification_channels", "last_sent_at"),
    ("notification_logs", "created_at"),
    ("orders", "filled_at"),
    ("orders", "decided_at"),
    ("positions", "opened_at"),
    ("strategies", "last_signal_at"),
    ("strategies", "last_run_at"),
    ("tradingview_webhook_logs", "received_at"),
)


def upgrade() -> None:
    """Upgrade schema."""
    if op.get_bind().dialect.name != "postgresql":
        return
    for table, column in _COLUMNS:
        op.execute(
            sa.text(
                f'ALTER TABLE {table} ALTER COLUMN "{column}" '
                f"TYPE TIMESTAMP WITH TIME ZONE USING \"{column}\" AT TIME ZONE 'UTC'"
            )
        )


def downgrade() -> None:
    """Downgrade schema."""
    if op.get_bind().dialect.name != "postgresql":
        return
    for table, column in _COLUMNS:
        op.execute(
            sa.text(
                f'ALTER TABLE {table} ALTER COLUMN "{column}" '
                f"TYPE TIMESTAMP WITHOUT TIME ZONE USING \"{column}\" AT TIME ZONE 'UTC'"
            )
        )
