"""flag a tradingview alert that carries no id

Revision ID: fbbbbc022afd
Revises: c4ee0993ef5e
Create Date: 2026-08-19 22:26:35.075013

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fbbbbc022afd"
down_revision: str | Sequence[str] | None = "c4ee0993ef5e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tradingview_webhook_logs", schema=None) as batch_op:
        # server_default, because autogenerate wrote this NOT NULL with
        # nothing to fill it. false is right for the existing rows: they were
        # accepted before this flag existed and nobody can now say whether
        # they carried an id, so claiming they did not would be inventing a
        # warning about alerts that may be perfectly fine.
        batch_op.add_column(
            sa.Column("missing_id", sa.Boolean(), nullable=False, server_default=sa.false())
        )

    with op.batch_alter_table("tradingview_webhook_logs", schema=None) as batch_op:
        batch_op.alter_column("missing_id", server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tradingview_webhook_logs", schema=None) as batch_op:
        batch_op.drop_column("missing_id")

    # ### end Alembic commands ###
